apiVersion: v1
kind: Service
metadata:
  name: headroom-gui
  namespace: headroom
  labels:
    app: headroom-gui
spec:
  selector:
    app: headroom-gui
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
